### ISSUE TITLE
Dynamic link between Analytics Tool and the Wordpress Plugin

### ISSUE THREAD

**Issue by EijiTomonari** [PipeWebMonetization/analytics-tool#1]
@EijiTomonari will be responsible for the infrastructure flow

### Tasks
- [x] How o token will be stored and encrypted
- [x] Generate and store the token when a new user is created
- [x] Dynamically pull data from Dynamo using user session
- [ ] Setup API authentication

**Comment by EijiTomonari** [comment]
https://github.com/PipeWebMonetization/analytics-tool/pull/8
